src/objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <externalId>true</externalId>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <externalId>true</externalId>
        <label>First Name</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <externalId>true</externalId>
        <label>Last Name</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Skills__c</fullName>
        <label>Skills</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Skill_List</valueSetName>
        </valueSet>
    </fields>
    <label>Student</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Student Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Student_Scoring_Skill__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Skill__c</fullName>
        <label>Skill</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Skill_List</valueSetName>
        </valueSet>
    </fields>
    <label>Student Scoring Skill</label>
    <nameField>
        <displayFormat>SK-{0000}</displayFormat>
        <label>Student Scoring Skill Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student Scoring Skills</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Student_Skill__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Max_Point__c</fullName>
        <label>SPoint</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Skill__c</fullName>
        <label>Skill</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Skill_List</valueSetName>
        </valueSet>
    </fields>
    <label>Student Skill</label>
    <nameField>
        <displayFormat>SK-{0000}</displayFormat>
        <label>Student Skill Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student Skills</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SM_NewStudentTriggerTest.cls
/**
 * Created by nguyen.nghia@mulodo.com on 10/17/2017.
 */
@isTest
private class SM_NewStudentTriggerTest {
	@TestSetup static void setupData() {
		List<Student_Skill__c> skillList = new List<Student_Skill__c>();
		// get picklist values
		Schema.DescribeFieldResult studentSkills = Student_Skill__c.Skill__c.getDescribe();
		List<Schema.PicklistEntry> studentSkillOption = studentSkills.getPicklistValues();

		for(Schema.PicklistEntry skill: studentSkillOption) {
			skillList.add(new Student_Skill__c(
					Active__c = true,
					Skill__c = skill.getValue(),
					Max_Point__c = 500
			));
		}

		insert skillList;
	}
	@isTest static void testNewStudentTrigger() {
		// get picklist values
		Schema.DescribeFieldResult studentSkills = Student_Skill__c.Skill__c.getDescribe();
		List<Schema.PicklistEntry> studentSkillOption = studentSkills.getPicklistValues();

		String skillSet = studentSkillOption[0].getValue() + ';' + studentSkillOption[1].getValue(); // mock skill set
		System.debug(skillSet);
		Test.startTest();
			List<Student__c> mockStudentList = new List<Student__c>();
			for(Integer i = 0; i < 10; i++) {
				mockStudentList.add(new Student__c(
						First_Name__c = 'Nghia_'+ i,
						Last_Name__c = 'Nguyen_'+ i,
						Email__c = 'nguyen.nghia@mulodo.com',
						Skills__c = skillSet
				));
			}

			insert mockStudentList;
		Test.stopTest();

		System.assertEquals(20, [SELECT COUNT() FROM Student_Scoring_Skill__c], 'There should 20 student scoring skill should be insert');
	}
}