src/objects/Student_Skill__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Max_Point__c</fullName>
        <label>SPoint</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Skill__c</fullName>
        <label>Skill</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Skill_List</valueSetName>
        </valueSet>
    </fields>
    <label>Student Skill</label>
    <nameField>
        <displayFormat>SK-{0000}</displayFormat>
        <label>Student Skill Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student Skills</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SM_StudentSkillTriggerTest.cls
/**
 * Created by nguyen.nghia@mulodo.com on 10/17/2017.
 */
@isTest
private class SM_StudentSkillTriggerTest {

	@IsTest static void testStudentSkillTriggerTest() {
		Student_Skill__c conflictStudentSkill = new Student_Skill__c(
			Active__c = true,
				Skill__c = 'OOP',
				Max_Point__c = 500
		);
		insert conflictStudentSkill;
		Test.startTest();
		try {
			insert new Student_Skill__c(
					Active__c = true,
					Skill__c = 'OOP',
					Max_Point__c = 500);
		} catch(DmlException e) {
			System.assert(e.getMessage().contains('Skill with Skill Name: OOP is already existed'));
		}
		Test.stopTest();

	}

	/** Test case that when have 2 or more conflict Student Skill in inserted simultaneously
	*/
	@isTest static void testInsertDoubleConflict() {
		Student_Skill__c conflictStudentSkill = new Student_Skill__c(
				Active__c = true,
				Skill__c = 'OOP',
				Max_Point__c = 500
		);
		insert conflictStudentSkill;
		Test.startTest();
		List<Student_Skill__c> doubleConflictList = new List<Student_Skill__c>();
		doubleConflictList.add(new Student_Skill__c(
				Active__c = true,
				Skill__c = 'OOP',
				Max_Point__c = 500));
		doubleConflictList.add(new Student_Skill__c(
				Active__c = true,
				Skill__c = 'OOP',
				Max_Point__c = 700));
		try {
			insert doubleConflictList;
		} catch(DmlException e) {
			System.assert(e.getMessage().contains('Skill with Skill Name: OOP is already existed'));
		}
		Test.stopTest();
	}
}