src/objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>Level__c</fullName>
        <label>Level</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Fresher</fullName>
                </value>
                <value>
                    <fullName>Junior</fullName>
                </value>
                <value>
                    <fullName>Senior</fullName>
                </value>
                <value>
                    <fullName>Leader</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Scores__c</fullName>
        <label>Scores</label>
        <summarizedField>Student_Scoring_Skill__c.Points__c</summarizedField>
        <summaryForeignKey>Student_Scoring_Skill__c.Student_ID__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Student</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Student Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SM_StudentLevelQueable.cls
/**
 * Created by nguyen.nghia@mulodo.com on 10/18/2017.
 */
public class SM_StudentLevelQueable implements Queueable{

	public Void execute(System.QueueableContext context) {
		List<Student__c> recordList = [SELECT Scores__c, Level__c FROM Student__c];
		List<Student__c> updateList = new List<Student__c>();
		for(Student__c student: (List<Student__c>)recordList) {
			if (student.Scores__c >= 400) {
				student.Level__c = 'Leader';
			} else if (student.Scores__c >= 300) {
				student.Level__c = 'Senior';
			} else if (student.Scores__c >= 200) {
				student.Level__c = 'Junior';
			} else if (student.Scores__c >= 0) {
				student.Level__c = 'Fresher';
			}
			updateList.add(student);
		}
		update updateList;
	}
}