src/objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <externalId>true</externalId>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <externalId>true</externalId>
        <label>First Name</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <externalId>true</externalId>
        <label>Last Name</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Skills__c</fullName>
        <label>Skills</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Skill_List</valueSetName>
        </valueSet>
    </fields>
    <label>Student</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Student Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Student_Scoring_Skill__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Skill__c</fullName>
        <label>Skill</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Skill_List</valueSetName>
        </valueSet>
    </fields>
    <label>Student Scoring Skill</label>
    <nameField>
        <displayFormat>SK-{0000}</displayFormat>
        <label>Student Scoring Skill Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student Scoring Skills</pluralLabel>
    <recordTypes>
        <fullName>Java</fullName>
        <active>true</active>
        <description>Record Type for Java</description>
        <label>Java</label>
    </recordTypes>
    <recordTypes>
        <fullName>PHP</fullName>
        <active>true</active>
        <description>Record type for PHP Scoring</description>
        <label>PHP</label>
    </recordTypes>
    <recordTypes>
        <fullName>Salesforce</fullName>
        <active>true</active>
        <description>Record type for Salesforce</description>
        <label>Salesforce</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Student_Skill__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Max_Point__c</fullName>
        <label>SPoint</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Skill__c</fullName>
        <label>Skill</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Skill_List</valueSetName>
        </valueSet>
    </fields>
    <label>Student Skill</label>
    <nameField>
        <displayFormat>SK-{0000}</displayFormat>
        <label>Student Skill Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student Skills</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SM_StudentSkillsBatchTest.cls
/**
 * Created by nguyen.nghia@mulodo.com on 10/17/2017.
 */
@isTest
private class SM_StudentSkillsBatchTest {

	@TestSetup
	static void setupData() {
		List<Student_Skill__c> skillList;
		List<Student__c> mockStudentList = new List<Student__c>();
		List<RecordType> skillRT; // get recordType
		Map<String, Id> skillRTMap = new Map<String, Id>(); // map Name, Id from skillRT
		// get picklist values
		Schema.DescribeFieldResult studentSkills = Student_Skill__c.Skill__c.getDescribe();
		List<Schema.PicklistEntry> studentSkillOption = studentSkills.getPicklistValues();

		skillRT = [SELECT Name, Id FROM RecordType WHERE sObjectType = 'Student_Skill__c' and isActive = true];

		for(RecordType type: skillRT) {
			skillRTMap.put(type.Name, type.Id);
		}

		System.debug(studentSkillOption);

//		for(Schema.PicklistEntry skill: studentSkillOption) {
//			skillList.add(new Student_Skill__c(
//					Active__c = true,
//					Skill__c = skill.getLabel(),
//					Max_Point__c = 500
//					RecordType = skillRTMap.get('Java')
//			));
//		}
		skillList = new List<Student_Skill__c> {
				new Student_Skill__c(Active__c = true, RecordTypeId = skillRTMap.get('Java'), Skill__c = 'Java Basic Knowledge', Max_Point__c = 500),
				new Student_Skill__c(Active__c = true, RecordTypeId = skillRTMap.get('PHP'), Skill__c = 'OOP', Max_Point__c = 500),
				new Student_Skill__c(Active__c = true, RecordTypeId = skillRTMap.get('Salesforce'), Skill__c = 'Developer Beginner', Max_Point__c = 500),
				new Student_Skill__c(Active__c = true, RecordTypeId = skillRTMap.get('Java'), Skill__c = 'Redis', Max_Point__c = 500)
				};

		insert skillList;

		String skillSet = 'Java Basic Knowledge;Redis'; // mock skill set

		for(Integer i = 0; i < 10; i++) {
			mockStudentList.add(new Student__c(
					First_Name__c = 'Nghia_'+ i,
					Last_Name__c = 'Nguyen_'+ i,
					Email__c = 'nguyen.nghia@mulodo.com',
					Skills__c = skillSet
			));
		}

		insert mockStudentList;
	}

	@isTest static void testNewStudentSkillBatch() {
		Test.startTest();
			SM_StudentSkillsBatch skillBatch = new SM_StudentSkillsBatch();
			Database.executeBatch(skillBatch);
		Test.stopTest();

		System.assertEquals(20, [SELECT COUNT() FROM Student_Scoring_Skill__c], 'There should 20 student scoring skill should be insert');
	}

	/** In this test case
	*	We will update an existed student (add new skill)
	*	Expect the scoring skill list will be 21 instead of 20 in the previous test case
	*/
	@isTest static void testExistedStudentSkillBatch() {
		Student__c student = [SELECT Id, Skills__c FROM Student__c WHERE First_Name__c =: 'Nghia_0'];
		student.Skills__c += ';OOP';

		Test.startTest();
			update student;
			SM_StudentSkillsBatch skillBatch = new SM_StudentSkillsBatch();
			Database.executeBatch(skillBatch);
		Test.stopTest();
		System.assertEquals(21, [SELECT COUNT() FROM Student_Scoring_Skill__c], 'There should 21 student scoring skill should be insert');

	}

}